ali_rezaee = [ 1, "ali rezaee", 18, 1234567890, "0987654321"]
a = "hello world"
# print(len(a))
# print(len(ali_rezaee))
print(ali_rezaee[0])
print(ali_rezaee[1])
print(ali_rezaee[2])
print(ali_rezaee[3])
print(ali_rezaee[4])
print()
print(ali_rezaee[-1])
print(ali_rezaee[-2])
print(ali_rezaee[-3])
print(ali_rezaee[-4])
print(ali_rezaee[-5])
print()
print(ali_rezaee[0:2])
print(ali_rezaee[1:4])
print(ali_rezaee[4:1:-1])
print(ali_rezaee)
print(ali_rezaee[::-1])
print(ali_rezaee[-4:-1:-1])
